// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJww43DTOtLK1qb3_2_OsSSlDIHmPS83M',
    appId: '1:253284033176:web:ee77b7be75b7723842a6ed',
    messagingSenderId: '253284033176',
    projectId: 'groceryvais',
    authDomain: 'groceryvais.firebaseapp.com',
    storageBucket: 'groceryvais.firebasestorage.app',
    measurementId: 'G-VZ5NT7341H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2gOv9jlVCO57i3pznYvA6MO-NSxlUGDQ',
    appId: '1:253284033176:android:c04b1f8365931e7542a6ed',
    messagingSenderId: '253284033176',
    projectId: 'groceryvais',
    storageBucket: 'groceryvais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6qbP6J_phJxdhgYJZRb7mVJJuOPCeBQ',
    appId: '1:742348971841:ios:2d5d6b0d7f86815832cbc0',
    messagingSenderId: '742348971841',
    projectId: 'authapp-f1942',
    storageBucket: 'authapp-f1942.firebasestorage.app',
    iosBundleId: 'com.example.groceryClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6qbP6J_phJxdhgYJZRb7mVJJuOPCeBQ',
    appId: '1:742348971841:ios:2d5d6b0d7f86815832cbc0',
    messagingSenderId: '742348971841',
    projectId: 'authapp-f1942',
    storageBucket: 'authapp-f1942.firebasestorage.app',
    iosBundleId: 'com.example.groceryClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4XSLIry9EcTZqt7m94nu7o5TCJ8NUkzc',
    appId: '1:742348971841:web:c151a5882009318132cbc0',
    messagingSenderId: '742348971841',
    projectId: 'authapp-f1942',
    authDomain: 'authapp-f1942.firebaseapp.com',
    storageBucket: 'authapp-f1942.firebasestorage.app',
    measurementId: 'G-84Q7BJSVXW',
  );

}